#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include <xtd/startup.h>

import heliumpp.gui.forms.main_form;

startup_(heliumpp::helium_main_form_class);
#pragma endregion
